name: nasa_explorer
description: Una app Flutter que explora el cosmos usando la API de NASA
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.4

  # HTTP & Network
  dio: ^5.3.2
  connectivity_plus: ^5.0.1
  pretty_dio_logger: ^1.3.1

  # Local Storage & Cache
  shared_preferences: ^2.2.2

  # Image Loading & Caching
  cached_network_image: ^3.3.0

  # UI Components
  flutter_staggered_grid_view: ^0.7.0

  # Utils
  intl: ^0.18.1
  url_launcher: ^6.2.1

  # JSON Serialization - AGREGAR ESTAS DEPENDENCIAS
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Build runner para generar código - AGREGAR ESTO
  build_runner: ^2.4.7

flutter:
  uses-material-design: true